{
  "sksl": {
    "entrypoint": "arcane_blur_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 u_size;\nuniform float u_intensity;\nuniform shader u_texture_input;\nuniform half2 u_texture_input_size;\n\nvec4 frag_color;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nfloat FLT_flutter_local_rand(vec2 uv)\n{\n    float a = dot(uv, vec2(92.0, 80.0));\n    float b = dot(uv, vec2(41.0, 62.0));\n    float x = sin(a) + (cos(b) * 51.0);\n    return fract(x * 1000.0);\n}\n\nvec4 FLT_flutter_local_randColor(vec2 uv, float intensity)\n{\n    vec2 param = uv;\n    vec2 param_1 = uv.yx;\n    vec2 param_2 = uv.yx;\n    vec2 param_3 = uv;\n    return vec4((FLT_flutter_local_rand(param) * intensity) * ((FLT_flutter_local_rand(param_1) * 2.0) - 1.0), (FLT_flutter_local_rand(param_2) * intensity) * ((FLT_flutter_local_rand(param_3) * 2.0) - 1.0), 0.0, 1.0);\n}\n\nvec2 FLT_flutter_local_dist(vec2 pos)\n{\n    vec2 param = pos;\n    float param_1 = u_intensity;\n    return pos + ((FLT_flutter_local_randColor(param, param_1).xy * 0.00999999977648258209228515625) * 2.0);\n}\n\nvoid FLT_main()\n{\n    vec2 uv = FLT_flutter_local_FlutterFragCoord() / u_size;\n    vec2 param_2 = uv;\n    frag_color = u_texture_input.eval(u_texture_input_size * ( FLT_flutter_local_dist(param_2)));\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return frag_color;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "u_size",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "u_intensity",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 2,
        "name": "u_texture_input",
        "rows": 1,
        "type": 12
      }
    ]
  }
}