{
  "sksl": {
    "entrypoint": "black_hole_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform float uTime;\nuniform vec2 uSize;\nuniform float uSpeed;\nuniform float uPower;\nuniform vec2 uFocal;\nuniform float uScale;\nuniform vec3 uColor;\nuniform vec2 uDirection;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 fragCoord = FLT_flutter_local_FlutterFragCoord();\n    vec2 uv = (((fragCoord * 2.0) - uSize) * 1.5) / vec2(uSize.y);\n    vec2 mouse = (((uFocal * 2.0) - uSize) * 1.5) / vec2(uSize.y);\n    vec2 offset = vec2(cos((uTime * uSpeed) / uDirection.x) * mouse.x, sin((uTime * uSpeed) / uDirection.y) * mouse.y);\n    float light = 0.100000001490116119384765625 / distance(normalize(uv), uv);\n    if (length(uv) < 1.0)\n    {\n        light *= (0.100000001490116119384765625 / distance(normalize(uv - offset), uv - offset));\n    }\n    light = pow(light, uPower);\n    fragColor = vec4(uColor * light, light);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uTime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uSpeed",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "uPower",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 4,
        "name": "uFocal",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 5,
        "name": "uScale",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 6,
        "name": "uColor",
        "rows": 3,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 7,
        "name": "uDirection",
        "rows": 2,
        "type": 10
      }
    ]
  }
}