{
  "sksl": {
    "entrypoint": "cascade_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform float uTime;\nuniform vec2 uSize;\nuniform float uThick;\nuniform float uRepeats;\nuniform float uScale;\nuniform float uShimmer;\nuniform vec3 uColor;\nuniform float uPower;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvec3 FLT_flutter_local_palette(float t)\n{\n    vec3 a = uColor;\n    vec3 b = vec3(0.5);\n    vec3 c = vec3(1.0);\n    vec3 d = vec3(0.263000011444091796875, 0.41600000858306884765625, 0.556999981403350830078125);\n    return a + ((b * uShimmer) * cos(((c * t) + d) * ((1.0 / uScale) * 6.28318023681640625)));\n}\n\nvoid FLT_main()\n{\n    vec2 fragCoord = FLT_flutter_local_FlutterFragCoord();\n    vec2 uv = (((fragCoord * 2.0) - uSize) / vec2(uSize.y)) * uScale;\n    vec2 uv0 = uv;\n    vec4 finalColor = vec4(0.0);\n    for (float i = 0.0; i < 128.0; i += 1.0)\n    {\n        if (i < 0.0)\n        {\n            break;\n        }\n        if (i > uRepeats)\n        {\n            break;\n        }\n        uv = fract((uv * 1.5) * uThick) - vec2(0.5);\n        float d_1 = length(uv) * exp(-length(uv0));\n        float param = (length(uv0) + (i * 0.4000000059604644775390625)) + (uTime * 0.4000000059604644775390625);\n        vec3 col = FLT_flutter_local_palette(param);\n        d_1 = sin((d_1 * 8.0) + uTime) / 8.0;\n        d_1 = abs(d_1);\n        d_1 = pow(0.00999999977648258209228515625 / d_1, 1.2000000476837158203125);\n        finalColor += vec4(col * d_1, d_1);\n    }\n    float al = pow(1.0 - (length(fragCoord - (uSize / vec2(2.0))) / (uSize.y / 2.0)), uPower);\n    fragColor = vec4((finalColor.xyz / vec3(finalColor.w)) * al, al);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uTime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uThick",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "uRepeats",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 4,
        "name": "uScale",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 5,
        "name": "uShimmer",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 6,
        "name": "uColor",
        "rows": 3,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 7,
        "name": "uPower",
        "rows": 1,
        "type": 10
      }
    ]
  }
}