{
  "sksl": {
    "entrypoint": "frost_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 iResolution;\nuniform float progress;\nuniform shader image;\nuniform half2 image_size;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nfloat FLT_flutter_local_rand(vec2 uv)\n{\n    float a = dot(uv, vec2(92.0, 80.0));\n    float b = dot(uv, vec2(41.0, 62.0));\n    float x = sin(a) + (cos(b) * 51.0);\n    return fract(x);\n}\n\nvoid FLT_main()\n{\n    vec2 fragCoord = FLT_flutter_local_FlutterFragCoord();\n    vec2 uv_1 = fragCoord / iResolution;\n    vec4 d = image.eval(image_size * ( uv_1));\n    vec2 param = uv_1 + vec2(d.x * 0.0500000007450580596923828125);\n    vec2 param_1 = uv_1 + vec2(d.z * 0.0500000007450580596923828125);\n    vec2 rnd = vec2(FLT_flutter_local_rand(param), FLT_flutter_local_rand(param_1));\n    vec2 lensRadius = vec2(progress, 0.0500000007450580596923828125);\n    float dist = distance(uv_1, vec2(0.5));\n    float vigfin = pow(1.0 - smoothstep(lensRadius.x, lensRadius.y, dist), 2.0);\n    rnd *= (vec2(0.02500000037252902984619140625 * vigfin) + ((d.xy * 2.0) * vigfin));\n    uv_1 += rnd;\n    fragColor = mix(image.eval(image_size * ( uv_1)), vec4(0.699999988079071044921875, 1.0, 1.0, 1.0), vec4(rnd.x) * 1.0);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "iResolution",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "progress",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 2,
        "name": "image",
        "rows": 1,
        "type": 12
      }
    ]
  }
}