{
  "sksl": {
    "entrypoint": "lux_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform float uTime;\nuniform vec2 uSize;\nuniform float uThick;\nuniform float uRepeats;\nuniform float uScale;\nuniform float uShimmer;\nuniform vec3 uColor;\nuniform float uPower;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 fragCoord = FLT_flutter_local_FlutterFragCoord();\n    float z = uTime;\n    float l;\n    vec3 c;\n    for (int i = 0; i < 3; i++)\n    {\n        vec2 p = fragCoord / uSize;\n        vec2 uv = p;\n        p -= vec2(0.5);\n        p.x *= (uSize.x / uSize.y);\n        z += (uShimmer * 0.070000000298023223876953125);\n        l = length(p) * uScale;\n        uv += (((p / vec2(l)) * (sin(z) + 1.0)) * abs(sin(((l * uRepeats) - z) - z)));\n        c[i] = (0.00999999977648258209228515625 * uThick) / length(mod(uv, vec2(1.0)) - vec2(0.5));\n    }\n    vec3 color = (c / vec3(l)) * uColor;\n    float al = uTime * 2.0;\n    al = pow(1.0 - (length(fragCoord - (uSize / vec2(2.0))) / (uSize.y / 2.0)), uPower);\n    fragColor = vec4(color * al, al);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uTime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uThick",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "uRepeats",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 4,
        "name": "uScale",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 5,
        "name": "uShimmer",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 6,
        "name": "uColor",
        "rows": 3,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 7,
        "name": "uPower",
        "rows": 1,
        "type": 10
      }
    ]
  }
}