{
  "sksl": {
    "entrypoint": "pixelate_blur_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 iResolution;\nuniform float samples;\nuniform float pixelSize;\nuniform float radius;\nuniform shader uTexture;\nuniform half2 uTexture_size;\n\nvec4 FragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 fragCoord = FLT_flutter_local_FlutterFragCoord();\n    vec2 uv = fragCoord / iResolution;\n    vec2 pixelatedUV = (floor((uv * iResolution) / vec2(pixelSize)) * pixelSize) / iResolution;\n    vec4 col = vec4(0.0);\n    int iSamples = int(floor(samples));\n    if (iSamples < 1)\n    {\n        iSamples = 1;\n    }\n    if (iSamples > 25)\n    {\n        iSamples = 25;\n    }\n    int halfSamples = iSamples / 2;\n    for (int x = -25; x <= 25; x++)\n    {\n        if (x < (-halfSamples))\n        {\n            continue;\n        }\n        if (x > halfSamples)\n        {\n            break;\n        }\n        for (int y = -25; y <= 25; y++)\n        {\n            if (y < (-halfSamples))\n            {\n                continue;\n            }\n            if (y > halfSamples)\n            {\n                break;\n            }\n            vec2 samplePos = pixelatedUV + (vec2(float(x), float(y)) * (vec2(radius) / iResolution));\n            col += uTexture.eval(uTexture_size * ( samplePos));\n        }\n    }\n    float total = float((iSamples + 1) * (iSamples + 1));\n    col /= vec4(total);\n    FragColor = col;\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return FragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "iResolution",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "samples",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "pixelSize",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "radius",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 4,
        "name": "uTexture",
        "rows": 1,
        "type": 12
      }
    ]
  }
}